---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: clickhouse-analytics-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: clickhouse-initdb
  labels:
    app: clickhouse-analytics
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS analyticsdb;
    CREATE TABLE IF NOT EXISTS analyticsdb.analytics (
        page_views UInt32,
        clicks UInt32,
        scroll_depth UInt32,
        page_time Float32,
        session_time Float32
    ) ENGINE = MergeTree() ORDER BY tuple();
---
apiVersion: v1
kind: Service
metadata:
  name: clickhouse-analytics
spec:
  ports:
    - port: 8123
  selector:
    app: clickhouse-analytics
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clickhouse-analytics
spec:
  selector:
    matchLabels:
      app: clickhouse-analytics
  template:
    metadata:
      labels:
        app: clickhouse-analytics
    spec:
      containers:
      - name: clickhouse
        image: clickhouse/clickhouse-server:latest
        ports:
        - containerPort: 8123
        volumeMounts:
        - name: clickhouse-storage
          mountPath: /var/lib/clickhouse
        - name: initdb
          mountPath: /docker-entrypoint-initdb.d
      volumes:
      - name: clickhouse-storage
        persistentVolumeClaim:
          claimName: clickhouse-analytics-pvc
      - name: initdb
        configMap:
          name: clickhouse-initdb
