apiVersion: v1
kind: ConfigMap
metadata:
  name: clickhouse-initdb
  labels:
    app: clickhouse-analytics
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS analyticsdb;
    CREATE TABLE IF NOT EXISTS analyticsdb.analytics (
        page_views UInt32,
        clicks UInt32,
        scroll_depth UInt32,
        page_time Float32,
        session_time Float32
    ) ENGINE = MergeTree() ORDER BY tuple();

  config.xml: |
    <?xml version="1.0"?>
    <yandex>
        <logger>
            <level>trace</level>
            <console>true</console>
        </logger>
        
        <http_port>8123</http_port>
        <tcp_port>9000</tcp_port>
        <mysql_port>9004</mysql_port>
        
        <protocols>
            <mysql>
                <port>9004</port>
                <allow_public_key_retrieval>1</allow_public_key_retrieval>
            </mysql>
        </protocols>
        
        <listen_host>::</listen_host>
        <listen_host>0.0.0.0</listen_host>
        
        <max_connections>4096</max_connections>
        <keep_alive_timeout>3</keep_alive_timeout>
        <max_concurrent_queries>100</max_concurrent_queries>
        
        <uncompressed_cache_size>8589934592</uncompressed_cache_size>
        <mark_cache_size>5368709120</mark_cache_size>
        
        <path>/var/lib/clickhouse/</path>
        <tmp_path>/var/lib/clickhouse/tmp/</tmp_path>
        <user_files_path>/var/lib/clickhouse/user_files/</user_files_path>
        
        <users_config>users.xml</users_config>
        
        <default_profile>default</default_profile>
        <default_database>default</default_database>
        
        <timezone>UTC</timezone>
        
        <mlock_executable>false</mlock_executable>
        
        <remote_servers>
            <test_shard_localhost>
                <shard>
                    <replica>
                        <host>localhost</host>
                        <port>9000</port>
                    </replica>
                </shard>
            </test_shard_localhost>
        </remote_servers>
        
        <zookeeper incl="zookeeper-servers" optional="true" />
        <macros incl="macros" optional="true" />
        
        <builtin_dictionaries_reload_interval>3600</builtin_dictionaries_reload_interval>
        
        <max_session_timeout>3600</max_session_timeout>
        <default_session_timeout>60</default_session_timeout>
        
        <query_log>
            <database>system</database>
            <table>query_log</table>
            <flush_interval_milliseconds>7500</flush_interval_milliseconds>
        </query_log>
        
        <dictionaries_config>*_dictionary.xml</dictionaries_config>
    </yandex>