apiVersion: v1
kind: ConfigMap
metadata:
  name: clickhouse-mysql-config
data:
  mysql-config.xml: |
    <clickhouse>
        <mysql_port>9004</mysql_port>
        <protocols>
            <mysql>
                <port>9004</port>
                <socket>/var/run/clickhouse-server/clickhouse-mysql.sock</socket>
                <ssl_config>
                    <verificationMode>none</verificationMode>
                    <loadDefaultCAFile>false</loadDefaultCAFile>
                    <cacheSessions>true</cacheSessions>
                    <requireTLSv1_2>false</requireTLSv1_2>
                </ssl_config>
            </mysql>
        </protocols>
        <query_log>
            <database>system</database>
            <table>query_log</table>
            <partition_by>toYYYYMM(event_date)</partition_by>
            <flush_interval_milliseconds>7500</flush_interval_milliseconds>
        </query_log>
        <max_connections>4096</max_connections>
        <keep_alive_timeout>10</keep_alive_timeout>
        <max_concurrent_queries>100</max_concurrent_queries>
        <uncompressed_cache_size>8589934592</uncompressed_cache_size>
        <mark_cache_size>5368709120</mark_cache_size>
    </clickhouse>