apiVersion: v1
kind: ConfigMap
metadata:
  name: clickhouse-initdb
  labels:
    app: clickhouse-analytics
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS analyticsdb;
    CREATE USER IF NOT EXISTS ludx IDENTIFIED WITH plaintext_password BY 'ludx';
    GRANT ALL ON analyticsdb.* TO ludx;
    CREATE TABLE IF NOT EXISTS analyticsdb.analytics (
        page_views UInt32,
        clicks UInt32,
        scroll_depth UInt32,
        page_time Float32,
        session_time Float32
    ) ENGINE = MergeTree() ORDER BY tuple();