apiVersion: v1
kind: Service
metadata:
  name: clickhouse-analytics
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  selector:
    app: clickhouse-analytics
  ports:
    - name: http
      port: 8123
      targetPort: 8123