name: Deploy to EKS

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Login to Amazon ECR
        run: aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 734842486567.dkr.ecr.us-east-2.amazonaws.com

      - name: Build and push Docker image
        run: |
          docker build -t 734842486567.dkr.ecr.us-east-2.amazonaws.com/cmm707/analytics-service:latest .
          docker push 734842486567.dkr.ecr.us-east-2.amazonaws.com/cmm707/analytics-service:latest

      - name: Update kubeconfig
        run:  aws eks --region us-east-2 update-kubeconfig --name lugx-gaming-cluster

      - name: Set up kubeconfig
        run: |
          echo "${{ secrets.KUBECONFIG }}" > kubeconfig
          export KUBECONFIG=$PWD/kubeconfig

      - name: Create AWS Secret in Kubernetes
        run: |
          kubectl create secret generic aws-credentials \
            --from-literal=AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} \
            --from-literal=AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} \
            --dry-run=client -o yaml | kubectl apply -f -

      - name: Deploy to EKS
        run: |
          kubectl apply -f k8s/clickhouse-pvc.yaml
          kubectl apply -f k8s/clickhouse-configmap.yaml
          kubectl apply -f k8s/clickhouse-service.yaml
          kubectl apply -f k8s/clickhouse-deployment.yaml
          kubectl apply -f k8s/analytics-service.yaml
          kubectl apply -f k8s/analytics-deployment.yaml